function show_page3_data() {
    page3List_div('#Core1_BESS_Status');
    page3List_div('#Core2_BESS_Status');
    page3List_div('#Core1_Cube1');
    page3List_div('#Core1_Cube2');
    page3List_div('#Core1_Cube3');
    page3List_div('#Core1_Cube4');
    page3List_div('#Core2_Cube1');
    page3List_div('#Core2_Cube2');
    page3List_div('#Core2_Cube3');
    page3List_div('#Core2_Cube4');
}
function page3List_div(selector) {
    $(selector).empty();
    //console.log(selector);
    switch (selector)
    {
        case '#Core1_BESS_Status':
            $(selector).append(
                '<table id="tb_BESS_Status" class="table">'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">系統模式</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">直流電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">直流電流(A)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">直流功率(kW)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">平均電芯電壓(V)</span></th></tr>'
                + '<tr><td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_Mode + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_V + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_I + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_P + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Vmax + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Vmin + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Vavg + '</span></td></tr>'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">SOC(%)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">SOH(%)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最小電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">平均電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">可用電量(kWh)</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SOC + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SOH + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Tmax + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Tmin + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Tavg + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_+ '</span></td></tr></table>');
            break;
        case '#Core2_BESS_Status':
            $(selector).append(
                '<table id="tb_BESS_Status" class="table">'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">系統模式</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">直流電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">直流電流(A)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">直流功率(kW)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">平均電芯電壓(V)</span></th></tr>'
                + '<tr><td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_Mode + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_V + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_I + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_P + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Vmax + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Vmin + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Vavg + '</span></td></tr>'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">SOC(%)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">SOH(%)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">最小電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">平均電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 16px;">可用電量(kWh)</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SOC + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SOH + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Tmax + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Tmin + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].Cell_Tavg + '</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">' + FLN_bms_PCS_data[0].SYS_ + '</span></td></tr></table>');
            break;
        case '#Core1_Cube1':
            $(selector).append(
                '<table id="tb_Cube1" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[0].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[0].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[0].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[0].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[0].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[0].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[0].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[0].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[0].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[0].UPS_status + '</span></td></tr></table>');
            break;
        case '#Core1_Cube2':
            $(selector).append(
                '<table id="tb_Cube2" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[1].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[1].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[1].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[1].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[1].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[1].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[1].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[1].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[1].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[1].UPS_status + '</span></td></tr></table>');
            break;
        case '#Core1_Cube3':
            $(selector).append(
                '<table id="tb_Cube1" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[2].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[2].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[2].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[2].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[2].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[2].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[2].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[2].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[2].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[2].UPS_status + '</span></td></tr></table>');
            break;
        case '#Core1_Cube4':
            $(selector).append(
                '<table id="tb_Cube1" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[3].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[3].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[3].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[3].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[3].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[3].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[3].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[3].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[3].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[3].UPS_status + '</span></td></tr></table>');
            break;
        case '#Core2_Cube1':
            $(selector).append(
                '<table id="tb_Cube1" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[0].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[0].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[0].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[0].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[0].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[0].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[0].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[0].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[0].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[0].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[0].UPS_status + '</span></td></tr></table>');
            break;
        case '#Core2_Cube2':
            $(selector).append(
                '<table id="tb_Cube2" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[1].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[1].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[1].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[1].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[1].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[1].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[1].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[1].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[1].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[1].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[1].UPS_status + '</span></td></tr></table>');
            break;
        case '#Core2_Cube3':
            $(selector).append(
                '<table id="tb_Cube1" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[2].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[2].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[2].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[2].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[2].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[2].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[2].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[2].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[2].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[2].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[2].UPS_status + '</span></td></tr></table>');
            break;
        case '#Core2_Cube4':
            $(selector).append(
                '<table id="tb_Cube1" class="table">'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>電流(A)</span></th>'
                + '<th style="text-align: center;"><span>功率(kW)</span></th>'
                + '<th style="text-align: center;"><span>SOC(%)</span></th>'
                + '<th style="text-align: center;"><span>SOH(%)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack1_V + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_I + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_P + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_SOC + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_SOH + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack2_V + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_I + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_P + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_SOC + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_SOH + '</td></tr>'
                + '<tr><th style="text-align: center;"><span>Rack資料</span></th>'
                + '<th style="text-align: center;"><span>最大電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>平均電芯電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>最大電芯溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>最小電芯溫度(°C)</span></th></tr>'
                + '<tr><td><span>Rack1</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack1_Tmin + '</td></tr>'
                + '<tr><td><span>Rack2</span></td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Vmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Vmin + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Vavg + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Tmax + '</td>'
                + '<td>' + FLN_Cube_data[3].Rack2_Tmin + '</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="10" style="text-align: center;" ><span>HVAC</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>室外溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度1(%)</span></th>'
                + '<th style="text-align: center;"><span>室內溫度(°C)</span></th>'
                + '<th style="text-align: center;"><span>濕度2(%)</span></th>'
                + '<th style="text-align: center;"><span>空調狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[3].HVAC1_T_outdoor + '</td>'
                + '<td>' + FLN_Cube_data[3].HVAC2_Hum1 + '</td>'
                + '<td>' + FLN_Cube_data[3].HVAC1_T_indoor + '</td>'
                + '<td>' + FLN_Cube_data[3].HVAC2_Hum2 + '</td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[3].HVAC_Status + '</span></td></tr>'
                + '<tr><th colspan="10" style="text-align: center;"><span>UPS</span></th></tr>'
                + '<tr><th style="text-align: center;"><span>充電功率(P)</span></th>'
                + '<th style="text-align: center;"><span>電池電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電壓(V)</span></th>'
                + '<th style="text-align: center;"><span>輸入電流(A)</span></th>'
                + '<th style="text-align: center;"><span>UPS狀態</span></th></tr>'
                + '<tr><td>' + FLN_Cube_data[3].UPS_Charge_P + '</td>'
                + '<td>' + FLN_Cube_data[3].UPS_Vbatt + '</td>'
                + '<td>' + FLN_Cube_data[3].UPS_Vin + '</td>'
                + '<td>' + FLN_Cube_data[3].UPS_Iin + '</td>'
                + '<td><span class="label label-success label" style="font-weight: bold; font-size: 20px;">' + FLN_Cube_data[3].UPS_status + '</span></td></tr></table>');
            break;
        
    }

}