function show_page2_data() {
    page2List_div('#MVCB_div');
    page2List_div('#VCB1_div');
    page2List_div('#VCB2_div');
    page2List_div('#VCB3_div');
    page2List_div('#AUX_div'); 
}
function page2List_div(selector) {
    $(selector).empty();
    switch (selector) {
        case '#MVCB_div':
            $(selector).append(
                '<table id="table" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">MVCB盤電表(Nexus1500+)</span></th></tr>'
                +'<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電表資訊</span></th>'
                +'<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">相電壓(V)</span></th>'
                +'<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電流(A)</span></th>'
                +'<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率(kW)</span></th>'
                +'<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛功(kvar)</span></th>'
                +'<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">視在功率(kVA)</span></th>'
                +'<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率因數(PF)</span></th>'
                +'<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">線電壓(V)</span></th></tr>'
                +'<tr><td><span style="font-weight: bold; font-size: 20px;">三相</span></td>'
                +'<td>0.0</td>'
                +'<td>0.0</td>'
                + '<td>' + Nexus_Hs_data[0].HS_W.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_VAR.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_VA.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_PF.toFixed(3) + '</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">三線</span></td>'
                +'<td>0.0</td></tr>'
                +'<tr><td><span style="font-weight: bold; font-size: 20px;">R相</span></td>'
                + '<td>' + Nexus_Hs_data[0].HS_Van.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_Ia.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_A_W.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_A_VAR.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_A_VA.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_A_PF.toFixed(3) + '</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">A-B</span></td>'
                + '<td>' + Nexus_Hs_data[0].HS_Vab.toFixed(3) + '</td></tr>'
                +'<tr><td><span style="font-weight: bold; font-size: 20px;">S相</span></td>'
                + '<td>' + Nexus_Hs_data[0].HS_Vbn.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_Ib.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_B_W.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_B_VAR.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_B_VA.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_B_PF.toFixed(3) + '</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">B-C</span></td>'
                + '<td>' + Nexus_Hs_data[0].HS_Vbc.toFixed(3) + '</td></tr>'
                +'<tr><td><span style="font-weight: bold; font-size: 20px;">T相</span></td>'
                + '<td>' + Nexus_Hs_data[0].HS_Vcn.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_Ic.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_C_W.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_C_VAR.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_C_VA.toFixed(3) + '</td>'
                + '<td>' + Nexus_Hs_data[0].HS_C_PF.toFixed(3) + '</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">C-A</span></td>'
                + '<td>' + Nexus_Hs_data[0].HS_Vca.toFixed(3) + '</td></tr></table>'
                +'<table id="table1" class="table">'
                +'<tr><th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">實功電(kWh)</span></th>'
                +'<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛供電量(kVARH)</span></th>'
                +'<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">其他</span></th></tr>'
                +'<tr><td><span style="font-weight: bold; font-size: 20px;">充電</span></td>'
                +'<td>0.0</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                +'<td>0.0</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">頻率(Hz)</span></td>'
                + '<td>' + Nexus_Hs_data[0].HS_Freq.toFixed(3) + '</td> </tr>'
                +'<tr><td><span style="font-weight: bold; font-size: 20px;">放電</span></td>'
                +'<td>0.0</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                +'<td>0.0</td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">中性電壓(A)</span></td>'
                +'<td>0.0</td></tr></table>'
                +'<table id="table2" class="table">'
                +'<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">保護電驛(P3U30)</span></th></tr>'
                +'<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">50/50N</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">59</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">81H</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">27</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr>'
                +'<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">51/51N</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">59N</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">81L</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                +'<td><span style="font-weight: bold; font-size: 20px;">67</span></td>'
                +'<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr></table>');
            break;
        case '#VCB1_div':
            $(selector).append(
                '<table id="table" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">VCB盤1電表(PM5350)</span></th></tr>'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電表資訊</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">相電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電流(A)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率(kW)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛功(kvar)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">視在功率(kVA)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率因數(PF)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">線電壓(V)</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">三相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">三線</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">R相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">A-B</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">S相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">B-C</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">T相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">C-A</span></td>'
                + '<td>22.82k</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">實功電(kWh)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛供電量(kVARH)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">其他</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">充電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">頻率(Hz)</span></td>'
                + '<td>60.05</td> </tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">放電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">中性電壓(A)</span></td>'
                + '<td>0.0</td></tr></table>'
                + '<table id="table2" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">保護電驛(P1-FLYER)</span></th></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">50/50N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81H</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">27</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">51/51N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81L</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">67</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr></table>');
            break;
        case '#VCB2_div':
            $(selector).append(
                '<table id="table" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">VCB盤2電表(PM5350)</span></th></tr>'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電表資訊</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">相電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電流(A)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率(kW)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛功(kvar)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">視在功率(kVA)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率因數(PF)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">線電壓(V)</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">三相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">三線</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">R相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">A-B</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">S相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">B-C</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">T相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">C-A</span></td>'
                + '<td>22.82k</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">實功電(kWh)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛供電量(kVARH)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">其他</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">充電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">頻率(Hz)</span></td>'
                + '<td>60.05</td> </tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">放電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">中性電壓(A)</span></td>'
                + '<td>0.0</td></tr></table>'
                + '<table id="table2" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">保護電驛(P1-FLYER)</span></th></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">50/50N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81H</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">27</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">51/51N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81L</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">67</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr></table>');
            break;
        case '#VCB3_div':
            $(selector).append(
                '<table id="table" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">VCB盤3電表(PM5350)</span></th></tr>'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電表資訊</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">相電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電流(A)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率(kW)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛功(kvar)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">視在功率(kVA)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率因數(PF)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">線電壓(V)</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">三相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">三線</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">R相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">A-B</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">S相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">B-C</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">T相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">C-A</span></td>'
                + '<td>22.82k</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">實功電(kWh)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛供電量(kVARH)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">其他</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">充電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">頻率(Hz)</span></td>'
                + '<td>60.05</td> </tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">放電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">中性電壓(A)</span></td>'
                + '<td>0.0</td></tr></table>'
                + '<table id="table2" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">保護電驛(P1-FLYER)</span></th></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">50/50N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81H</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">27</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">51/51N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81L</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">67</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr></table>');
            break;
        case '#AUX_div':
            $(selector).append(
                '<table id="table" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">AUX盤電表(PM5350)</span></th></tr>'
                + '<tr><th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電表資訊</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">相電壓(V)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">電流(A)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率(kW)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛功(kvar)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">視在功率(kVA)</span></th>'
                + '<th style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">功率因數(PF)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">線電壓(V)</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">三相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">三線</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">R相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">A-B</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">S相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">B-C</span></td>'
                + '<td>22.82k</td></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">T相</span></td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">C-A</span></td>'
                + '<td>22.82k</td></tr></table>'
                + '<table id="table1" class="table">'
                + '<tr><th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">實功電(kWh)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">虛供電量(kVARH)</span></th>'
                + '<th colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">其他</span></th></tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">充電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">頻率(Hz)</span></td>'
                + '<td>60.05</td> </tr>'
                + '<tr><td><span style="font-weight: bold; font-size: 20px;">放電</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">電感性</span></td>'
                + '<td>0.0</td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">中性電壓(A)</span></td>'
                + '<td>0.0</td></tr></table>'
                + '<table id="table2" class="table">'
                + '<tr><th colspan="9" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">保護電驛(P1-FLYER)</span></th></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">50/50N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81H</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">27</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr>'
                + '<tr><td colspan="2" style="text-align: center;"><span style="font-weight: bold; font-size: 20px;">51/51N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">59N</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">81L</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td>'
                + '<td><span style="font-weight: bold; font-size: 20px;">67</span></td>'
                + '<td><span class="label label-success" style="font-weight: bold; font-size: 20px;">正常</span></td></tr></table>');
            break;

    }
}